# Site Information
title: Shameless
description: "ac"
url: https://ac.shameless.top/
repo: acshameless/ac
lang: zh-CN
timezone: Africa/El_Aaiun

# Social Media and External URLs
github: acshameless
zhihu: 
twitter: acshameless
v2ex: 
menu:
  - title: "Categories"
    url: "/categories.html"
  - title: "Weekly"
    url: "https://weekly.shameless.top/"
  - title: "About"
    url: "/about.html"
  - title: "SAP Notes"
    url: "https://sap.shameless.top/"
  - title: "Algo Notes"
    url: "https://algo.shameless.top/"

# SEO and Analytics
google_analytics: 

# Build Settings
paginate: 10
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true
future: true
highlighter: rouge
markdown: kramdown
permalink: /:year-:month-:day/:title.html
sass:
  sass_dir: _sass
  style: compressed

collections:
  posts:
    output: true
    permalink: /:year-:month-:day/:title.html
  posts_en:
    output: true
    permalink: /en/:year-:month-:day/:title.html
    sort_by: date

include: [".htaccess"]
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "LICENSE",
    "package.json",
    "node_modules",
  ]

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-pdf-embed
  - jekyll-sitemap
  - jekyll-feed

# Custom Site Settings
showBuyCoffee: true
payImage: 
assetUrl: 
defaultImage: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
